/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.lab.vues;

import javax.swing.JOptionPane;
import org.lab.dao.Dao;
import org.lab.entites.Utilisateur;

/**
 *
 * @author J-P
 */
public class Inscription extends javax.swing.JDialog {

    /**
     * Creates new form Inscription
     */
    public Inscription(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IHM_valider = new javax.swing.JButton();
        IHM_DejaInscrit = new javax.swing.JButton();
        IHM_nomut = new javax.swing.JTextField();
        IHM_verificationmotpasse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IHM_motpasse = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Nom utilsateur ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 80, 100, 30);

        jLabel2.setText("INSCRIPTION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 10, 110, 40);

        jLabel3.setText("Confirmation ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 190, 100, 30);

        IHM_valider.setText("Valider");
        IHM_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IHM_validerActionPerformed(evt);
            }
        });
        jPanel1.add(IHM_valider);
        IHM_valider.setBounds(270, 260, 90, 30);

        IHM_DejaInscrit.setText("Déjà Inscrit");
        IHM_DejaInscrit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IHM_DejaInscritActionPerformed(evt);
            }
        });
        jPanel1.add(IHM_DejaInscrit);
        IHM_DejaInscrit.setBounds(140, 260, 90, 30);

        IHM_nomut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IHM_nomutActionPerformed(evt);
            }
        });
        jPanel1.add(IHM_nomut);
        IHM_nomut.setBounds(140, 70, 130, 30);
        jPanel1.add(IHM_verificationmotpasse);
        IHM_verificationmotpasse.setBounds(140, 190, 140, 30);

        jLabel4.setText("Mot de Passe");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 130, 120, 30);
        jPanel1.add(IHM_motpasse);
        IHM_motpasse.setBounds(140, 130, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 20, 440, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IHM_nomutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IHM_nomutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IHM_nomutActionPerformed

    private void IHM_DejaInscritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IHM_DejaInscritActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login(new java.awt.Frame(), true);
        login.setVisible(true);
    }//GEN-LAST:event_IHM_DejaInscritActionPerformed

    private void IHM_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IHM_validerActionPerformed
        // TODO add your handling code here:
        Utilisateur user = new Utilisateur();
        String pseudo = IHM_nomut.getText();
        String password = IHM_motpasse.getText();
        String verifierpassword = IHM_verificationmotpasse.getText();
        if (pseudo.isEmpty() || password.isEmpty() || verifierpassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez insérer tous vos données entrées");
        } else if (!password.equalsIgnoreCase(verifierpassword) ) {
            JOptionPane.showMessageDialog(this, "Veuillez vérifier vos données entrées");

        } else {
            Dao dao = new Dao();
            dao.init();
            user.setNomut(pseudo);
            user.setMotpasse(password);
            dao.prepare(user);
            dao.save();
            JOptionPane.showMessageDialog(this, "Inscription validée");

            this.dispose();
            Login login = new Login(new java.awt.Frame(), true);
            login.setVisible(true);
            dao.close();
        }

    }//GEN-LAST:event_IHM_validerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inscription dialog = new Inscription(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IHM_DejaInscrit;
    private javax.swing.JTextField IHM_motpasse;
    private javax.swing.JTextField IHM_nomut;
    private javax.swing.JButton IHM_valider;
    private javax.swing.JTextField IHM_verificationmotpasse;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
